name: Flutter iOS Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Regenerate iOS files
        run: |
          rm -rf ios/Podfile
          flutter create . --platforms=ios

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile not found even after create" && exit 1
          fi

      - name: Build iOS (.app)
        run: flutter build ios --release --no-codesign

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
